---
settings:
  parallel: true

driver: 
  name: vagrant

provisioner: 
  name: chef_zero
  require_chef_omnibus: latest

attributes:
  authorization:
    sudo:
      users:
        - ubuntu
        - vagrant
      passwordless: true
  ha_disabled: true
  omnibus_updater:
    disabled: true
  tz: GMT

platforms:
- name: ubuntu-12.04
- name: centos-6.4

suites:
- name: bootstrap
  run_list:
  - recipe[ktc-base::bootstrap]
 
- name: default
  run_list:
  - recipe[ktc-testing]
  - recipe[etcd::compile_time]
  - recipe[ktc-monitor::client]
  - recipe[ktc-base]
  attributes:
    etcd:
      args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
      servers:
        - 127.0.0.1
