---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 1024

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04
  - name: centos-6.5-chef10
    driver_config:
      box_url:  http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.5_chef-provisionerless.box
      require_chef_omnibus: 10.30.2
suites: 
  - name: hosts
    run_list:
      - recipe[badhosts_test]
      - recipe[ktc-base::hosts]

  - name: bootstrap
    run_list:
      - recipe[ktc-testing]
      - recipe[ktc-base::bootstrap]
    attributes:
      authorization:
        sudo:
          users:
            - ubuntu
            - vagrant
          passwordless: true
      ha_disabled: true
      omnibus_updater:
        disabled: true
      tz: GMT
      etcd:
        args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
        servers:
          - 127.0.0.1
   
  - name: default
    run_list:
      - recipe[ktc-testing]
      - recipe[etcd::compile_time]
      - recipe[ktc-monitor::client]
      - recipe[ktc-base]
    attributes:
      authorization:
        sudo:
          users:
            - ubuntu
            - vagrant
          passwordless: true
      ha_disabled: true
      omnibus_updater:
        disabled: true
      tz: GMT
      etcd:
        args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
        servers:
          - 127.0.0.1
